/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockmain.cpp"

static const char* CMockString_RA_HIST_SECONDS = "RA_HIST_SECONDS";
static const char* CMockString_raPressure = "raPressure";

typedef struct _CMOCK_raPressure_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RunningAverage ReturnVal;
  RA_FREQUENCY* Expected_RA_HIST_SECONDS;

} CMOCK_raPressure_CALL_INSTANCE;

static struct MockmainInstance
{
  CMOCK_MEM_INDEX_TYPE raPressure_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmain_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.raPressure_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_raPressure);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockmain_Init(void)
{
  Mockmain_Destroy();
}

void Mockmain_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

RunningAverage raPressure(RA_FREQUENCY* RA_HIST_SECONDS)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_raPressure_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_raPressure);
  cmock_call_instance = (CMOCK_raPressure_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.raPressure_CallInstance);
  Mock.raPressure_CallInstance = CMock_Guts_MemNext(Mock.raPressure_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_raPressure,CMockString_RA_HIST_SECONDS);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_RA_HIST_SECONDS), (void*)(RA_HIST_SECONDS), sizeof(RA_FREQUENCY), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_raPressure(CMOCK_raPressure_CALL_INSTANCE* cmock_call_instance, RA_FREQUENCY* RA_HIST_SECONDS);
void CMockExpectParameters_raPressure(CMOCK_raPressure_CALL_INSTANCE* cmock_call_instance, RA_FREQUENCY* RA_HIST_SECONDS)
{
  cmock_call_instance->Expected_RA_HIST_SECONDS = RA_HIST_SECONDS;
}

void raPressure_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RA_FREQUENCY* RA_HIST_SECONDS, RunningAverage cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_raPressure_CALL_INSTANCE));
  CMOCK_raPressure_CALL_INSTANCE* cmock_call_instance = (CMOCK_raPressure_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.raPressure_CallInstance = CMock_Guts_MemChain(Mock.raPressure_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_raPressure(cmock_call_instance, RA_HIST_SECONDS);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(RunningAverage[sizeof(cmock_to_return) == sizeof(RunningAverage) ? 1 : -1])); /* add RunningAverage to :treat_as_array if this causes an error */
}

