/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKMAIN_H
#define _MOCKMAIN_H

#include "unity.h"
#include "main.cpp"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockmain_Init(void);
void Mockmain_Destroy(void);
void Mockmain_Verify(void);




#define raPressure_ExpectAndReturn(RA_HIST_SECONDS, cmock_retval) raPressure_CMockExpectAndReturn(__LINE__, RA_HIST_SECONDS, cmock_retval)
void raPressure_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RA_FREQUENCY* RA_HIST_SECONDS, RunningAverage cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
