/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockmain.h"

static const char* CMockString_beep_motor = "beep_motor";
static const char* CMockString_f1 = "f1";
static const char* CMockString_f2 = "f2";
static const char* CMockString_f3 = "f3";

typedef struct _CMOCK_beep_motor_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int Expected_f1;
  int Expected_f2;
  int Expected_f3;

} CMOCK_beep_motor_CALL_INSTANCE;

static struct MockmainInstance
{
  CMOCK_MEM_INDEX_TYPE beep_motor_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmain_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.beep_motor_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_beep_motor);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockmain_Init(void)
{
  Mockmain_Destroy();
}

void Mockmain_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void beep_motor(int f1, int f2, int f3)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_beep_motor_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_beep_motor);
  cmock_call_instance = (CMOCK_beep_motor_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.beep_motor_CallInstance);
  Mock.beep_motor_CallInstance = CMock_Guts_MemNext(Mock.beep_motor_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_beep_motor,CMockString_f1);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_f1, f1, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_beep_motor,CMockString_f2);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_f2, f2, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_beep_motor,CMockString_f3);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_f3, f3, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_beep_motor(CMOCK_beep_motor_CALL_INSTANCE* cmock_call_instance, int f1, int f2, int f3);
void CMockExpectParameters_beep_motor(CMOCK_beep_motor_CALL_INSTANCE* cmock_call_instance, int f1, int f2, int f3)
{
  cmock_call_instance->Expected_f1 = f1;
  cmock_call_instance->Expected_f2 = f2;
  cmock_call_instance->Expected_f3 = f3;
}

void beep_motor_CMockExpect(UNITY_LINE_TYPE cmock_line, int f1, int f2, int f3)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_beep_motor_CALL_INSTANCE));
  CMOCK_beep_motor_CALL_INSTANCE* cmock_call_instance = (CMOCK_beep_motor_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.beep_motor_CallInstance = CMock_Guts_MemChain(Mock.beep_motor_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_beep_motor(cmock_call_instance, f1, f2, f3);
}

